import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Huting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/apple-icon-60x60.png"
        />{" "}
        /
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/apple-icon-72x72.png"
        />{" "}
        /
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/apple-icon-76x76.png"
        />{" "}
        /
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/apple-icon-114x114. /png"
        />{" "}
        /
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/apple-icon-120x120. /png"
        />
        <link
          rel="apple-touch-icon"
          sizes="144x144"
          href="/apple-icon-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/android-icon-192x /192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />{" "}
        /
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/favicon-96x96.png"
        />{" "}
        /
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      <nav>
        <ul className={styles.nav_ul}>
          <a href="/">
            <li>Home</li>
          </a>
          <a href="/About">
            <li>About</li>
          </a>
          <a href="/contact">
            <li>Contact</li>
          </a>
          <a href="/Documentation">
            <li>Docs</li>
          </a>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting <a href="/">Coders!</a>
        </h1>
        <p className={styles.description}>
          A blog by Hunting <code>Coder</code> for Hunting <code>Coders</code>
        </p>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam,
              in?
            </p>
            <Image
              src={
                "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
              }
              alt="Picture of the author"
              width={500}
              height={400}
            />
          </div>

          <div className={styles.card}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam,
              in?
            </p>
            <Image
              src={
                "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
              }
              alt="Picture of the author"
              width={500}
              height={400}
            />
          </div>

          <div className={styles.card}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam,
              in?
            </p>
            <Image
              src={
                "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
              }
              alt="Picture of the author"
              width={500}
              height={400}
            />
          </div>

          <div className={styles.card}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam,
              in?
            </p>
            <Image
              src={
                "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
              }
              alt="Picture of the author"
              width={500}
              height={400}
            />
          </div>
          <div className={styles.card}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam,
              in?
            </p>
            <Image
              src={
                "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
              }
              alt="Picture of the author"
              width={500}
              height={400}
            />
          </div>

          <div className={styles.card}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam,
              in?
            </p>

            <Image
              src={
                "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
              }
              alt="Picture of the author"
              width={500}
              height={400}
            />
          </div>

          <div className={styles.card}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam,
              in?
            </p>
            <Image
              src={
                "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
              }
              alt="Picture of the author"
              width={500}
              height={400}
            />
          </div>

          <div className={styles.card}>
            <h3>How to learn JavaScript in 2022</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam,
              in?
            </p>
            <Image
              src={
                "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
              }
              alt="Picture of the author"
              width={500}
              height={400}
            />
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://www.microsoft.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Microsoft Inc.
        </a>
      </footer>
    </div>
  );
}
